FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml turbo.json ./
RUN npm i -g pnpm
COPY . .
RUN pnpm install
RUN pnpm run build --filter identity-svc...

FROM node:20-alpine
WORKDIR /app
RUN npm i -g pnpm
COPY --from=builder /app /app
EXPOSE 3001
CMD pnpm run start:prod --filter identity-svc
